import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "react-hot-toast"; // Import Toaster

import MobileNav from "@/components/MobileNav";

import DesktopNav from "@/components/DesktopNav";
import ThemeObserver from "@/components/ThemeObserver";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
    
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Theme >
          {modal}
          <div className="flex min-h-screen dark:bg-black dark:text-white ">
            <DesktopNav />
            <div className="pb-24 lg:pb-4 pt-4 px-4 lg:px-8 w-full flex justify-around">
              <div className="w-full">{children}</div>
            </div>
          </div>
          <MobileNav />
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                background: "#4C1D95", // Purple-900
                color: "#fff",
                padding: "16px",
                borderRadius: "8px",
              },
              success: {
                iconTheme: {
                  primary: "#8B5CF6", // Purple-500
                  secondary: "#fff",
                },
                style: {
                  background: "#4C1D95",
                  border: "1px solid #7C3AED", // Purple-600
                },
              },
              error: {
                style: {
                  background: "#7f1d1d", // Red-900
                  border: "1px solid #dc2626", // Red-600
                },
              },
              loading: {
                style: {
                  background: "#4C1D95",
                  border: "1px solid #7C3AED",
                },
              },
            }}
          />
        </Theme>
        <ThemeObserver />
      </body>
    </html>
  );
}
